### ISSUE TITLE
History summarization crashes non-tool agents: _summarize_context uses self.tool_llm, which only AgentWithTools sets

### ISSUE THREAD

**Issue by BrennanTM** [lanl/ursa#295]
`_summarize_context` calls `self.tool_llm.invoke(to_summarize)` (base.py:915), but `tool_llm` is only assigned in `AgentWithTools` (base.py:1566). Agents that inherit from plain `BaseAgent`, such as `BasicChatAgent` and `PromptingAgent`, have no `tool_llm` attribute, so the first time a conversation crosses `tokens_before_summarize` the summarization step raises `AttributeError` and the run dies.

Repro:

```python
from ursa.agents.chat_agent import BasicChatAgent
from langchain_core.messages import AIMessage, HumanMessage

agent = BasicChatAgent(llm=some_model, workspace=ws, tokens_before_summarize=1, messages_to_keep=2)
history = []
for i in range(4):
    history.append(HumanMessage(f"question {i} " + "pad " * 60))
    history.append(AIMessage(f"answer {i} " + "pad " * 60))
history.append(HumanMessage("final question"))
agent.invoke({"messages": history})
# AttributeError: 'BasicChatAgent' object has no attribute 'tool_llm'
```

With default settings this needs a long session (50k approximate tokens) to trigger, which is presumably why it has not surfaced: short sessions never summarize, and the agents most likely to run long (chat with tools, execution) happen to inherit `AgentWithTools`.

Simplest fix: fall back to `self.llm` when `tool_llm` is absent, or assign `self.tool_llm = self.llm` in `BaseAgent` so subclasses override it. Happy to submit the one-line fix with a regression test.

Found while extending the regression coverage proposed in #289.

**Comment by mikegros** [comment]
Thanks for finding this edge. 

I think your suggested fix is reasonable but I think we might go a different direction with that shortly and make most user-facing agents AgentsWithTools. There are a bunch of benefits to this and I hope to get that change in soon. 

One aspect relevant to this though is that changing to use self.llm for non-tool using agents can actually be a problem with mixed agent history. For instance:
Suppose an agent had tools, like the execution or chat agent, and was persisted with `--name`. Then you wanted to have that persistent agent act like a planner or hypothesizer. If the summarization triggered, it would have a history with tool calls so using self.llm would fail in attempting to summarize. 

I think your suggested change would still be welcome after a change like that, because there are some non-tool using agents that we would like to avoid this failure mode you note here. But for a lot of the user-facing agents I think we want to move toward making tools available to them.

I will keep this open as a reminder to make sure it gets fully addressed and fixed before the next tag.

**Comment by BrennanTM** [comment]
I dug into your mixed-history case and can confirm it empirically, with one sharpening: the client-side converter passes tool blocks through untouched, so the failure is server-side. Anthropic rejects with "Requests which include tool_use or tool_result blocks must define tools", and as far as I can tell that rule is not documented anywhere; OpenAI's own samples replay tool-bearing history with no tools parameter at all, so it enforces only pairing and ordering. Your instinct was right, and it is an Anthropic-path failure specifically.

That pushed me to survey how other frameworks summarize tool-bearing histories (langmem, Anthropic's server-side compaction, OpenAI's session memory, Letta). The strongest precedent turns out to be Anthropic's own compaction: it replaces the summarized span entirely with prose, so no live tool blocks survive inside a summarized region.

I built and tested that shape against the summarizer here: render the summarized span, tool calls and results included, to a plain-text transcript before invoking the summarizer, call it through tool_llm when present or llm otherwise, and land the summary as a human message. Results: the strict-xfail repros for this issue and #296 that I pinned in #297 before writing any fix all flip to passing; your persisted-agent-with-tool-history case summarizes cleanly on a plain BaseAgent with a prose-only request (verified through the real langchain-anthropic converter: zero tool blocks); the post-summarization request ends on a human turn; and the full suite shows no regressions.

This stays compatible with the AgentsWithTools direction you described: it makes the summarizer provider-valid under any model, bound or unbound, so it works the same before and after that change. Happy to open the PR whenever it suits your sequencing; it stacks naturally on #297, since the pins there become its regression tests.
